### ISSUE TITLE
Incompatible format conversion when compiled with Mac OS

### ISSUE THREAD

**Issue by tantratron** [rdelien/fsxx_keygen#1]
The function encrypt returns uint32_t format but the reprint result attempts using format %010u which creates a compiler (2 errors and 3 warnings).

Copy-paste from the Xcode terminal shell... the reason being that Apple OS uses as predated **_encrypt_** then the conflict here since encrypt is a function with different parameters definition.

./encryption.h:15:10: error: conflicting types for 'encrypt'
uint32_t encrypt(uint32_t seed, uint32_t serialnr);
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:549:7: note: previous declaration is here
void     encrypt(char *, int) __DARWIN_ALIAS(encrypt);
         ^
main.c:202:43: warning: incompatible integer to pointer conversion passing 'const uint32_t' (aka 'const unsigned int')
      to parameter of type 'char *' [-Wint-conversion]
                fprintf(stdout, "%010u - %s\n", encrypt(seeds[instrument->options[ndx].seed_ndx], serialnr), ins...
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:549:21: note: passing argument to
      parameter here
void     encrypt(char *, int) __DARWIN_ALIAS(encrypt);
                       ^
main.c:202:35: error: argument type 'void' is incomplete
                fprintf(stdout, "%010u - %s\n", encrypt(seeds[instrument->options[ndx].seed_ndx], serialnr), ins...
                                                ^
main.c:215:49: warning: incompatible integer to pointer conversion passing 'const uint32_t' (aka 'const unsigned int')
      to parameter of type 'char *' [-Wint-conversion]
                fprintf(stdout, "%.3u: %010u\n", ndx, encrypt(seeds[ndx], serialnr));
                                                              ^~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:549:21: note: passing argument to
      parameter here
void     encrypt(char *, int) __DARWIN_ALIAS(encrypt);
                       ^
main.c:215:41: error: argument type 'void' is incomplete
                fprintf(stdout, "%.3u: %010u\n", ndx, encrypt(seeds[ndx], serialnr));
                                                      ^
2 warnings and 3 errors generated.

**Comment by rdelien** [comment]
Looking forward to your pull request!
